version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build the app
          command: npm run build

      - run:
          name: Deploy to GitHub Pages
          command: |
            git config user.email "circleci@example.com"
            git config user.name "CircleCI"
            git checkout --orphan gh-pages
            git --work-tree dist add --all
            git --work-tree dist commit -m "Deploy to GitHub Pages"
            git push origin HEAD:gh-pages --force

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
