import styled from "styled-components";
import { ReactComponent as InfoIcon } from '../icons/info-icon.svg';
import {useState} from "react";

const Text = styled.div`
  color: rgba(0, 0, 0, 0.5);
  font-weight: 700;
  font-size: 14px;
  line-height: 20px;
`;

const TheRealRoot = styled.div`
  width: 100%;
  position: relative;
`;

const Root = styled.div`
  //border-radius: 0 0 16px 16px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 16px 0 8px;
`;

const Delimiter = styled.div`
  position: absolute;
  width: calc(100% + 24px);
  transform: translateX(-12px);
  border-top: 1px solid rgba(0, 0, 0, 0.12);
`;

const InfoIconButton = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  width: 18px;
  cursor: pointer;
`;

const InfoBox = styled.div`
  padding: 8px 12px;
  position: absolute;
  max-width: 300px;
  width: 100%;
  left: calc(50% - 150px);
  top: calc(100% + 12px);
  background: #000000;
  opacity: 0.8;
  border-radius: 8px;
  color: rgba(255, 255, 255, 0.88);
  z-index: 40;
`;

export default function BotMessageBottom() {

  const [showInfoBox, setShowInfoBox] = useState(false);

  return <TheRealRoot>
    <Delimiter/>
    <Root>
      <Text>Generated by AI</Text>
      <InfoIconButton
        onMouseEnter={() => setShowInfoBox(true)}
        onMouseLeave={() => setShowInfoBox(false)}
      >
        <InfoIcon height={'28px'} width={'28px'}/>
      </InfoIconButton>
    </Root>
    {
      showInfoBox && <InfoBox>
        This response is based only on contents provided to Clark. It is generated by an AI and may not
        be fully accurate.
      </InfoBox>
    }
  </TheRealRoot>
}